hosts:
  server1:
    comment:
    url: https://mail.ru
    period: 1
    notification:
      phone: 7898
      email: mail@mail.ru
  server2:
    comment:
    url: http://ya.ru
    period: 1
    notification:
      phone: 7898

